In [1]:
import pandas as pd
import os

# Load the raw data
raw_file_path = "data/raw/owid-covid-data.csv"
df = pd.read_csv(raw_file_path)

# Show first 5 rows to understand the data
df.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-01-05,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-01-06,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-01-07,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-01-08,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-01-09,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772,NaN,NaN,NaN,NaN

In [3]:
# Keep only important columns
columns_to_keep = ['location', 'date', 'total_cases', 'new_cases', 'total_deaths']
df = df[columns_to_keep]

# Drop rows where 'location' is missing
df = df.dropna(subset=['location'])

# Fill missing values with 0
df[['total_cases', 'new_cases', 'total_deaths']] = df[['total_cases', 'new_cases', 'total_deaths']].fillna(0)

# Create new column: active_cases
df['active_cases'] = df['total_cases'] - df['total_deaths']

# Avoid negative active cases
df['active_cases'] = df['active_cases'].apply(lambda x: max(x, 0))

# Save cleaned data
os.makedirs('data/processed', exist_ok=True)
processed_file_path = "data/processed/cleaned_covid_data.csv"
df.to_csv(processed_file_path, index=False)

print(f"✅ Data cleaned and saved to {processed_file_path}")

✅ Data cleaned and saved to data/processed/cleaned_covid_data.csv